import typescript from "@rollup/plugin-typescript";
import resolve from "@rollup/plugin-node-resolve";
// import url from "@rollup/plugin-url";
import copy from "rollup-plugin-copy";
import json from "@rollup/plugin-json";
import fs from "fs";
import path from "path";

function convertModelToMemoryFormat(modelDir, outputFile) {
  try {
    const modelJsonPath = path.join(modelDir, "model.json");
    const modelJson = JSON.parse(fs.readFileSync(modelJsonPath, "utf8"));
    const weightsManifest = modelJson.weightsManifest;

    // Collect all weight data into a single ArrayBuffer
    const weightBuffers = [];
    let totalSize = 0;

    // Process each manifest entry
    const processedManifest = weightsManifest.map((manifest) => ({
      ...manifest,
      paths: manifest.paths.map((weightPath) => {
        const weightFile = fs.readFileSync(path.join(modelDir, weightPath));
        weightBuffers.push(weightFile);
        totalSize += weightFile.length;
        return weightPath; // Keep original path name for reference
      }),
    }));

    // Combine all weight buffers into a single buffer
    const combinedBuffer = Buffer.concat(weightBuffers, totalSize);

    // Convert to base64 for embedding in the TypeScript file
    const weightDataBase64 = combinedBuffer.toString("base64");

    const modelData = {
      modelTopology: modelJson.modelTopology,
      weightsManifest: processedManifest,
      // Include the weight data as base64 that will be converted to ArrayBuffer at runtime
      weightDataBase64: weightDataBase64,
    };

    const tsContent = `// Auto-generated by rollup plugin - do not edit manually
const modelData = ${JSON.stringify(modelData, null, 2)} as const;

// Convert base64 weight data to ArrayBuffer at runtime
const weightData = new Uint8Array(
  atob(modelData.weightDataBase64)
    .split('')
    .map(char => char.charCodeAt(0))
).buffer;

export default {
  modelTopology: modelData.modelTopology,
  weightsManifest: modelData.weightsManifest,
  weightData: weightData
} as const;`;

    fs.writeFileSync(outputFile, tsContent);
    console.log(
      `✓ Converted model: ${path.basename(modelDir)} (${(
        totalSize /
        1024 /
        1024
      ).toFixed(2)}MB)`
    );
  } catch (error) {
    console.error(`Failed to convert model ${modelDir}:`, error);
    throw error;
  }
}

// Custom plugin to convert TensorFlow models to proper fromMemory format
function tensorflowModelConverter() {
  return {
    name: "tensorflow-model-converter",
    buildStart() {
      // Convert models at the start of the build
      convertModelToMemoryFormat(
        "./src/models/keyboard",
        "./src/models/keyboard-model.ts"
      );
      convertModelToMemoryFormat(
        "./src/models/mouse",
        "./src/models/mouse-model.ts"
      );
    },
  };
}

export default {
  input: "src/index.ts",
  output: {
    dir: "dist",
    format: "umd",
    name: "bbotd",
    sourcemap: true,
    globals: {
      "@tensorflow/tfjs": "tf",
    },
  },
  external: ["@tensorflow/tfjs"],
  plugins: [
    resolve(),
    json(),
    typescript({
      tsconfig: "./tsconfig.json",
      declaration: true,
      declarationDir: "dist",
    }),
    // tensorflowModelConverter(),
    copy({
      targets: [
        {
          src: "public/models/*",
          dest: "dist/models",
        },
      ],
      verbose: true,
      hook: "buildEnd",
    }),
  ],
};
