[project]
name = "detecting-bots"
version = "0.1.0"
dependencies = [
    ""
]
requires-python = ">= 3.9"
authors = [
    {name = "Krystian Ogonowski", email = "krystian@ogonowski.it"},
    {name = "Łukasz Fijałkowski", email = "lukasz.fijalkowski@example.com"},
    {name = "Paweł Jurek", email = "pawel.jurek@example.com"},
]
description = "TODO: "
readme = "README.md"
license = "MIT"
keywords = ["bot", "detection"]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://example.com/docs"
Repository = "https://example.com/git/repo"
Issues = "https://github.com/me/spam/issues"
Changelog = "https://example.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]
lint = "ruff ."


