name: Build and deploy docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        working-directory: ./docs
        run: npm install

      - name: Build project
        working-directory: ./docs
        run: npm run docs:build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          destination_dir: docs
          keep_files: true
