name: Build and deploy React example

on:
  push:
    branches:
      - master
    paths:
      - "examples/react-ts/**"
      - ".github/workflows/react-example.yml"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        working-directory: ./examples/react-ts
        run: npm install

      - name: Build project
        working-directory: ./examples/react-ts
        run: npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/react-ts/dist
          destination_dir: react-ts
          keep_files: true
